<?php

/**
 * @file
 * Callbacks and hooks for this module.
 *
 * Intentionally hardcodes roles when building UI.
 * This is a custom module it doesn't need the configurability of permissions.
 */

/**
 * Implements hook_theme().
 */
function caldora_aeon_link_theme($existing, $type, $theme, $path) {
  return array(
    'caldora_aeon_link_object_display' => array(
      'template' => 'theme/caldora-aeon-link-object-display',
//      'pattern' => 'caldora_aeon_link_object_display__',
      'variables' => array(
        'object' => NULL,
        'aeon_metadata' => NULL,
       ),
    ),
  );
}

/**
 * Implements hook_block_info()
 */
function caldora_aeon_link_block_info() {
  $blocks = array();
  $blocks['build_aeon_link'] = array(
  'info' => t('AEON link.'),
  'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * COMMENTED OUT 9/29/14 to temporarily stop display of the block (bc)
 */
//function caldora_aeon_link_block_view($block_name = '') {
//  if ($block_name == 'build_aeon_link') {
//    $content = theme('caldora_aeon_link_object_display');
//    $block = array(
//    'subject' => t('Archives Request System'),
//    'content' => $content,
//  );
//  return $block;
//  }
//}

/**
 * Implements hook_islandora_required_objects().
 */
function caldora_aeon_link_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'caldora_aeon_link');

  // Caldora Content Model.
  $caldora_content_model = $connection->repository->constructObject('ct:imageCModel');
  $caldora_content_model->owner = 'fedoraAdmin';
  $caldora_content_model->label = 'Caltech Image Content Model';
  $caldora_content_model->models = 'fedora-system:ContentModel-3.0';

  // MODS Schema Datastream.
  $datastream = $caldora_content_model->constructDatastream('MODS_SCHEMA', 'M');
  $datastream->label = 'MODS Schema v3.4';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/data/datastreams/ct_imageCModel/MODS_SCHEMA.xml", FALSE);
  $caldora_content_model->ingestDatastream($datastream);

  return array(
    'caldora' => array(
      'title' => 'Caldora',
      'objects' => array(
        $caldora_content_model,
      ),
    ),
  );
}

/**
 *
 * Implements hook_preprocess_theme().   
 * Shameless hack.
 *
 */
function caldora_aeon_link_preprocess_caldora_image(&$variables) {
  module_load_include('inc', 'islandora', 'includes/datastream');
  module_load_include('inc', 'islandora', 'includes/solution_packs');
//  drupal_add_js('misc/form.js');
//  drupal_add_js('misc/collapse.js');
  $obj = $variables['object'];
  $repository = $obj->repository;
  // label/title
  $variables['label'] = $obj->label;

  // Make sure we have MODS.
  if ($obj['MODS']) {
    $xml = simplexml_load_string($obj['MODS']->content);
    $xml->registerXPathNamespace('mods', 'http://www.loc.gov/mods/v3');

    // Metadata storage.
    $metadata = array(
      array(
        'label' => t('Title'),
        'xpath' => '/mods:mods/mods:titleInfo/mods:title',
        'aeon_tag' => 'ItemSubTitle',
      ),
      array(
        'label' => t('Date Created'),
        'xpath' => '/mods:mods/mods:originInfo/mods:dateCreated',
        'aeon_tag' => 'ItemDate',
      ),
      array(
        'label' => t('ID Number'),
        'xpath' => '/mods:mods/mods:location/mods:shelfLocator',
        'aeon_tag' => 'CallNumber',
     ),
    );

    /*
     * Process metadata storage array, 
     * return table rows to be displayed.
     */
    $rows = array();
    foreach ($metadata as $value) {
      $row = caldora_aeon_link_metadata_standard($value['aeon_tag'], $value['xpath'], $xml);
      if ($row) {
        // remove any double quotes in the data--they will cause the string to be truncated
        // when it is passed to AEON;
        $row = str_replace('"', '%22', $row);
        $rows = array_merge($rows, $row);
      }
    }
//    $params = array(
//      'header' => array(),
//      'rows' => $rows,
//      'attributes' => array(),
//      'caption' => '',
//      'colgroups' => array(),
//      'sticky' => FALSE,
//      'empty' => '',
//    );
//    $variables['aeon_metadata'] = theme('table', $params);
    $variables['aeon_test_data'] = "AEON_TEST_DATA--";
    $variables['aeon_metadata'] = $rows;
  }  
//DEBUG
// $variables['aeon_test_data'] = "AEON_TEST_DATA: ";
// $variables['aeon_metadata'] = $rows;
// print_r ($variables['aeon_test_data']);
// print_r ($variables['aeon_metadata']);
// print_r ($variables['aeon_metadata']['ItemSubTitle']);
// print_r ($variables);
//END DEBUG
//return $rows;
}

/**
 * Take a label, xpath and xml, do some xpathing and text structuring.
 *
 * @param string $label
 *   The label for the metadata
 *
 * @param string $xpath
 *   The xpath to be used on the xml param
 *
 * @param SimpleXMLElement $xml
 *   The xml that the xpath is applied to
 *
 * @return array
 *  array containing metadata element values for each aeon element
 */
function caldora_aeon_link_metadata_standard($label = NULL, $xpath = NULL, SimpleXMLElement $xml = NULL) {
  $aeon_data = array();
  if ($label && $xpath && $xml) {
    try {
      $values = $xml->xpath($xpath);
      foreach ($values as $value) {
        $value = trim((string) $value);
        if ($value) {
          $aeon_data[$label] = $value;
        }
      }
    }
    catch (Exception $exc) {
      // Error handling.
    }
  }
// DEBUG
//  print_r ($aeon_data);
// END DEBUG
  return $aeon_data;
}
